version: '3.7'

services:

    db-postgres:
        image: postgres
        container_name: postgres-container
        restart: always
        environment:
            POSTGRES_DB: ""
            POSTGRES_USER: ""
            POSTGRES_PASSWORD: ""
        volumes: 
            - /var/lib/postgresql/db/data:/var/lib/postgresql/data
        ports:
            - "?:5432"
        networks:
            - postgres-network

    pgadmin-compose:
        image: dpage/pgadmin4
        container_name: pgadmin-container
        environment:
            PGADMIN_DEFAULT_EMAIL: ""
            PGADMIN_DEFAULT_PASSWORD: ""
        ports:
            - ""
        depends_on:
            - db-postgres
        networks:
            - postgres-network
    
networks: 
    postgres-network:
        driver: "bridge"